export interface DetaineeData {
id: string;
created_at?: string | null;
updated_at?: string | null;
firstname: string;
lastname: string;
birthdate: string;
sexe: string;
cell_id: string;
service_id: string;
priv_lib_id: string;
SSType?: string | null;
liberation_id: string;
trusted_contact_id: string;
isolement: string;
RplNum: string;
Salduz?: string | null;
DevRest?: Array<any> | null;
notice_id?: string | null;
user_created?: string | null;
Audition?: string | null;
PrintTrypt?: string | null;
contention_id?: string | null;
bac?: number | null;
Prohibe?: string | null;
incident_id?: string | null;
EqCharge?: string | null;
Avocate?: string | null;
ProhiValImp: string;
SurvCam?: string | null;
medical_id?: string | null;
};
